jwt:
  token:
#    secret: $2a$04$OwS2wsBqowyXnln/Ta3cWekghLwJ7gutMOfFyD4N5tFm3cWZGN3Ky
     secret: superSecretKey
     jwtExpirationMs: 3600000
     jwtRefreshExpirationMs: 86400000
spring:
  datasource:
    url: jdbc:h2:mem:social_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2
springdoc:
  swagger-ui:
    path: /swagger
#    url: /openapi.yaml
#  api-docs:
logging:
  level:
    web: debug
    root: debug
#    path: /api-docs